import Head from 'next/head'
import Image from 'next/image'
import { Main, CarouselSection, InformationSection, Title } from '../components/layout';
import { LocationList, LocationListItem } from '../components/location-information';
import { FeatureList } from '../components/feature-list';
import { CarouselItem, Carousel, Navigation } from '../components/carousel';
import { useEffect, useState } from 'react';
import axios from 'axios';

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    let mounted = true;
    axios.get('https://run.mocky.io/v3/8dac4388-ce28-4406-95bb-91aec813168d')
      .then(response => {
        if(mounted) {
          setData(response.data)
        }
      })
    return () => mounted = false;
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <InformationSection>
          <Title>Monsieur Didot</Title>
          <FeatureList>
            <li>4 people</li>
            <li>2 bedrooms</li>
            <li>2 bathrooms</li>
            <li>Private Terrace</li>
            <li>Peaceful</li>
          </FeatureList>
          <LocationList>
            <LocationListItem>Notting Hill, London</LocationListItem>
            <LocationListItem>Walk 6 mins (Westbourne Park Station)</LocationListItem>
            <LocationListItem>Stairs</LocationListItem>
          </LocationList>
        </InformationSection>
        <CarouselSection>
          <Carousel width="95%">
              {data?.imageUrls?.map((image, index) => 
                <CarouselItem key={index}>
                  <Image width={2000} height={1117} alt="image" src={image} />
                </CarouselItem>
              )}
          </Carousel>
          <Navigation />
        </CarouselSection>
      </Main>
    </>
  )
}
