import Head from 'next/head'
import Image from 'next/image'
import { Main, CarouselSection } from '../components/layout/Layout.styled';
import { CarouselItem } from '../components/carousel/Carousel.styled';
import { Carousel } from '../components/carousel/Carousel';
import { Navigation } from '../components/carousel/Navigation';
import { useEffect, useState } from 'react';
import axios from 'axios';

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    let mounted = true;
    axios.get('https://run.mocky.io/v3/8dac4388-ce28-4406-95bb-91aec813168d')
      .then(response => {
        if(mounted) {
          setData(response.data)
        }
      })
    return () => mounted = false;
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <CarouselSection>
          <Carousel width="95%">
              {data?.imageUrls?.map((image, index) => 
                <CarouselItem key={index}>
                  <Image width={2000} height={1117} alt="image" src={image} />
                </CarouselItem>
              )}
          </Carousel>
          <Navigation />
        </CarouselSection>
      </Main>
    </>
  )
}
